<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<section style="margin-top:55px;">

<div id="container" class=" pad-12 "> 
    <div class="white-block status-list pad-2 index" style="margin-bottom: 12px;background: #fff;">
        
     
        <div id="privacy">
			<h1>The 2014 Gobble Gobble Giveaway Official Rules</h1>
		
<h4>NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE WILL NOT ENHANCE CHANCES OF WINNING.  VOID WHERE PROHIBITED BY LAW . ALL FEDERAL, STATE, LOCAL, AND MUNICIPAL LAWS AND REGULATIONS APPLY. VOID WHERE PROHIBITED BY LAW .</h4>
<p>&#8220;The 2014 Gobble Gobble Giveaway&#8221;is open only to legal residents of the fifty (50) United States (including District of Columbia) who are eighteen (16) years or older at the time of entry. Participation constitutes entrant&#8217;s full and unconditional agreement to and acceptance of these Official Rules. &#8220;The 2014 Gobble Gobble Giveaway&#8221; begins at 9:00 a.m., Greenwich Mean Time ("GMT") on November 24, 2014 and ends at 11:59 p.m., ("GMT") on December 1, 2014 (&#8220;Entry Period&#8221;). Sweepstakes is sponsored by WomanFreebies.com, 1338 Wellington Street West &#8211; Unit 200, Ottawa, ON, K1Y 3B7 (the &#8220;Sponsors&#8221;), who are solely responsible for all aspects of this Sweepstakes.</p>
<p><strong>Eligibility:</strong> &#8220;The 2014 Gobble Gobble Giveaway&#8221; will run on WomanFreebies.com. The prizes hidden on WomanFreebies.com are available to all legal residents of the United States and District of Columbia who are 16 years of age or older as of the beginning of the Sweepstakes. Employees, officers, and directors (including immediate family members and members of the same household) of the Sponsors are not eligible to participate. The Promotion is subject to all applicable federal, state and local laws and regulations. Participation constitutes entrant's full and unconditional agreement to these Official Rules and Sponsor's decisions, which are final and binding in all matters related to the Promotion. Winning a prize is contingent upon<br />
fulfilling all requirements set forth herein. Only one major prize may be claimed per household per day.</p>
<p><strong>Prize Information:</strong> Over the course of the contest period, a minimum of $5,000 in prizes will be hidden on WomanFreebies.com. There will be a minimum of 800 Amazon Instant Delivery Gift Cards hidden on WomanFreebies.com (US Dollars). Products also to be given away on WomanFreebies.com, include, but are not limited to a, KitchenAid Artisan Mixer and HP 11.6&#8243; Stream 11-D010WM Laptop PC. The odds of winning depend on the number of visitors on the site and the number of prizes remaining. Different amounts of prizes will be added each day, and prizes that are not found may be re-hidden. Products can be won by American residents only and will not be shipped to any other countries, with the exception of American military bases overseas. All prizes are non exchangeable and have no redeemable cash value, and they will be processed within 48 hours of being claimed. WomanFreebies.com, is not responsible for gift cards that are lost or stolen, or for errors made on claim forms. All gift cards will be sent via Amazon Instant Delivery Gift Cards and you will claim in the email inbox that you provide.</p>
<p><strong>Entry Information:</strong> To win prizes, search through the blog posts on WomanFreebies.com. Participants must open Thanksgiving Pies on the blog WomanFreebies.com. Wins will not be honored for people who do not live in the USA. Participants may use any browser or device to participate. Thanksgiving Pies will display on every page on WomanFreebies.com and will never disappear until the user clicks it or leaves the page. Thanksgiving Pies will time out after 10 minutes and will be re-added. To claim a Thanksgiving Pie, click on it and a form will pop up. If it is a winner, user must enter their mailing and email address and click "Submit" to claim prize. WomanFreebies.com is not responsible for incorrect email information submitted. All winning Thanksgiving Pies will display a turkey inside. Each blog post has different odds of displaying a winning Thanksgiving Pie and no one is guaranteed to win.</p>
<p><strong>Disclosure of Information:</strong> All participants must submit an email address so that they can be contacted if they win (that is how all gift card prizes will be claimed). All information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the prize to the winner. WomanFreebies.com implements a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.</p>
<p><strong>Special Conditions:</strong> If for any reason, in the opinion of WomanFreebies.com, in their sole discretion, &#8220;The 2014 Gobble Gobble Giveaway&#8221;, is not capable of running as planned, including infection by computer virus, bugs, tampering, unauthorized intervention, fraud, technical failures, or any other causes beyond the control of WomanFreebies.com which corrupt or affect the administration, security, fairness, integrity, or proper conduct of this Sweepstakes, WomanFreebies.com reserves the right, at its sole discretion, to disqualify any individual who tampers with the entry process, and to cancel, terminate, modify, or suspend this Sweepstakes. In any such event, WomanFreebies.com, at its sole discretion, will randomly select the winner(s) from eligible, non-suspect entries received prior to the event requiring such termination, suspension or cancellation. The Released Parties assume no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, entries. The Released Parties are not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers, or providers, computer equipment, software, failure of any email or entry to be received by WomanFreebies.com on account of technical problems or traffic congestion on the Internet or at any Web site, or any combination thereof, including any injury or damage to participant's or any other person's computer related to or resulting from participation or downloading any materials in this Sweepstakes. CAUTION: ANY ATTEMPT TO DELIBERATELY DAMAGE ANY WEB SITE OR UNDERMINE THE LEGITIMATE OPERATION OF THIS SWEEPSTAKES MAY BE A VIOLATION OF CRIMINAL AND CIVIL LAWS AND SHOULD SUCH AN ATTEMPT BE MADE, SPONSOR RESERVES THE RIGHT TO SEEK DAMAGES TO THE FULLEST EXTENT PERMITTED BY LAW. Entries made by Internet will be declared made by the authorized account holder of the email address submitted at time of entry. "Authorized account holder" is defined as the natural person who is assigned to an email address by an Internet access provider, online service provider or other organization (e.g., business, educational, institution, etc.) that is responsible for assigning email addresses for the domain associated with the submitted email address.</p>
<p><strong>SPONSOR:</strong> This Sweepstakes is sponsored by WomanFreebies.com, 1338 Wellington Street West &#8211; Unit 200 Ottawa, ON, K1Y 3B7.</p>
<p><i>This Promotion is in no way sponsored, endorsed or administered by, or associated with, Facebook. You understand that you are providing your information to WomanFreebies.com and not to Facebook.</i></p>
<p><i>This Promotion is in no way sponsored, endorsed or administered by, or associated with any company other than WomanFreebies.com.</i></p>		
        
        </div>
        
            
        <div style="clear:both;"></div>  
        
     
    </div>
</div>
</section>

